const API_URL="https://script.google.com/macros/s/AKfycbwRCEflR8YEIAsFVCZsDDMORkau8dcyZjjJGnnGJRerNivD0ZFWH-OQop2IR-Q2F_b1/exec";
const COLLEGE_LOCATION={latitude:20.716,longitude:76.56222},ALLOWED_RADIUS=300;
let currentRole="",currentUser=null,currentLocation=null;
function showPage(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active")}
function showRolePage(){showPage("rolePage")}function showRegisterPage(){showPage("registerPage")}
function openLogin(role){currentRole=role;document.getElementById("loginForm").reset();document.getElementById("loginTitle").textContent=role+" Login";document.getElementById("username").classList.toggle("hidden",role!=="admin");document.getElementById("email").classList.toggle("hidden",role==="admin");document.getElementById("registerText").classList.toggle("hidden",role!=="student");showPage("loginPage")}
async function sendRequest(data){try{const r=await fetch(API_URL,{method:"POST",body:JSON.stringify(data)});return await r.json()}catch(e){return{status:"error",message:"Server connection failed"}}}
document.getElementById("loginForm").addEventListener("submit",async e=>{e.preventDefault();let d={action:"login",role:currentRole,password:password.value};if(currentRole==="admin")d.username=username.value.trim();else d.email=email.value.trim();let r=await sendRequest(d);if(r.status==="success"){currentUser=r.user;if(currentRole==="student"){studentName.textContent="Welcome, "+currentUser.name;showPage("studentDashboard")}else if(currentRole==="teacher"){teacherName.textContent="Welcome, "+currentUser.name;showPage("teacherDashboard")}else{showPage("adminDashboard");loadAdminData()}}else alert(r.message||"Login failed")});
document.getElementById("registerForm").addEventListener("submit",async e=>{e.preventDefault();let r=await sendRequest({action:"registerStudent",name:regName.value,email:regEmail.value,course:regCourse.value,year:regYear.value,password:regPassword.value});alert(r.message||r.status);if(r.status==="success")openLogin("student")});
function checkLocation(role){let el=document.getElementById(role==="student"?"studentLocationStatus":"teacherLocationStatus");navigator.geolocation.getCurrentPosition(p=>{let d=distance(p.coords.latitude,p.coords.longitude,COLLEGE_LOCATION.latitude,COLLEGE_LOCATION.longitude);if(d<=ALLOWED_RADIUS){currentLocation={latitude:p.coords.latitude,longitude:p.coords.longitude};el.textContent="✅ Inside College Area: "+Math.round(d)+"m";document.getElementById(role==="student"?"studentAttendanceBtn":"teacherAttendanceBtn").disabled=false}else el.textContent="❌ Outside College Area: "+Math.round(d)+"m"},()=>alert("Allow location permission"),{enableHighAccuracy:true,timeout:20000})}
function distance(a,b,c,d){const R=6371000,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180,v=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(v),Math.sqrt(1-v))}
async function markAttendance(){if(!currentLocation||!currentUser)return alert("Verify location first");let r=await sendRequest({action:"markAttendance",userID:currentUser.id,name:currentUser.name,role:currentRole,latitude:currentLocation.latitude,longitude:currentLocation.longitude});alert(r.message||r.status);loadAttendanceHistory()}
async function loadAttendanceHistory(){let el=document.getElementById(currentRole==="student"?"studentAttendanceList":"teacherAttendanceList");let r=await sendRequest({action:"getAttendance",userID:currentUser.id});el.textContent=JSON.stringify(r.attendance||[],null,2)}
async function loadAdminData(){let s=await sendRequest({action:"getStudents"}),t=await sendRequest({action:"getTeachers"}),a=await sendRequest({action:"getAttendance"});studentCount.textContent=(s.students||[]).length;teacherCount.textContent=(t.teachers||[]).length;adminAttendanceList.textContent=JSON.stringify(a.attendance||[],null,2)}
function logout(){currentRole="";currentUser=null;currentLocation=null;showPage("homePage")}